#!/usr/bin/env node
// Local development environment (BUILD-CONTRACT.md section 10).
// - Reads the running local Supabase stack (`supabase status -o env`).
// - Reuses keys already in apps/*/.env.local and .env.local; generates any that are missing.
// - Writes apps/web/.env.local, apps/worker/.env.local and the root .env.local (dev scheduler secrets).
// - Upserts the staff-assertion key and version pointers into the local Vault so the web mint side
//   and the SQL verifier agree (§14.2). Run it again after every `supabase db reset`.
// Prints variable NAMES only, never values.
import { execFileSync } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const files = {
  web: path.join(root, 'apps/web/.env.local'),
  worker: path.join(root, 'apps/worker/.env.local'),
  root: path.join(root, '.env.local'),
};

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]] = m[2].replace(/^"(.*)"$/, '$1');
  }
  return out;
}

function readEnv(file) {
  return existsSync(file) ? parseEnv(readFileSync(file, 'utf8')) : {};
}

function writeEnv(file, vars, header) {
  const body = Object.entries(vars).map(([k, v]) => `${k}=${v}`).join('\n');
  writeFileSync(file, `# ${header}\n# Generated by scripts/dev-env.mjs. Local development only; never commit.\n${body}\n`, { mode: 0o600 });
}

const key = () => randomBytes(32).toString('base64url');
const sha = (s) => createHash('sha256').update(s).digest('hex');

let status;
try {
  status = parseEnv(execFileSync('supabase', ['status', '-o', 'env'], { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }));
} catch {
  console.error('dev-env: the local Supabase stack is not running. Start it with `supabase start`.');
  process.exit(1);
}
const apiUrl = status.API_URL ?? 'http://127.0.0.1:55421';
const dbUrl = status.DB_URL ?? 'postgresql://postgres:postgres@127.0.0.1:55422/postgres';
const dbHost = new URL(dbUrl);

const prev = { ...readEnv(files.root), ...readEnv(files.worker), ...readEnv(files.web) };
const keep = (name, gen) => prev[name] || gen();

const shared = {
  STAFF_ASSERTION_KEY_CURRENT: keep('STAFF_ASSERTION_KEY_CURRENT', key),
  STAFF_ASSERTION_KEY_VERSION: prev.STAFF_ASSERTION_KEY_VERSION || '1',
  WORKER_DEV_SECRET: keep('WORKER_DEV_SECRET', key),
  SCHEDULER_BEARER: keep('SCHEDULER_BEARER', key),
  REVALIDATE_SECRET: keep('REVALIDATE_SECRET', key),
  READY_SECRET: keep('READY_SECRET', key),
};

const web = {
  DATABASE_URL: `postgresql://recover_web:recover_web_dev@${dbHost.host}/postgres`,
  DATABASE_SSL: 'disable',
  WEB_ORIGIN: 'http://localhost:3000',
  AUTH_SECRET: keep('AUTH_SECRET', key),
  AUTH_TRUST_HOST: 'true',
  AUTH_URL: 'http://localhost:3000/api/auth',
  AUTH_GOOGLE_ID: prev.AUTH_GOOGLE_ID || '',
  AUTH_GOOGLE_SECRET: prev.AUTH_GOOGLE_SECRET || '',
  RECOVER_DEV_LOGIN: '1',
  RECOVER_DEV_AUTH: '1',
  STAFF_ASSERTION_KEY_CURRENT: shared.STAFF_ASSERTION_KEY_CURRENT,
  STAFF_ASSERTION_KEY_VERSION: shared.STAFF_ASSERTION_KEY_VERSION,
  DEVICE_KEY_V1: keep('DEVICE_KEY_V1', key),
  IP_KEY: keep('IP_KEY', key),
  SEARCH_KEY: keep('SEARCH_KEY', key),
  WORKER_URL: 'http://localhost:3001',
  WORKER_DEV_SECRET: shared.WORKER_DEV_SECRET,
  STORAGE_PUBLIC_URL: `${apiUrl}/storage/v1/object/public`,
  S3_ORIGIN: new URL(apiUrl).origin,
  REVALIDATE_SECRET_SHA256: sha(shared.REVALIDATE_SECRET),
  READY_SECRET_SHA256: sha(shared.READY_SECRET),
};

const worker = {
  DATABASE_URL: `postgresql://recover_worker:recover_worker_dev@${dbHost.host}/postgres`,
  DATABASE_SSL: 'disable',
  SUPABASE_S3_ENDPOINT: status.STORAGE_S3_URL ?? `${apiUrl}/storage/v1/s3`,
  SUPABASE_S3_REGION: status.S3_PROTOCOL_REGION ?? 'local',
  SUPABASE_S3_ACCESS_KEY_ID: status.S3_PROTOCOL_ACCESS_KEY_ID ?? '',
  SUPABASE_S3_SECRET_ACCESS_KEY: status.S3_PROTOCOL_ACCESS_KEY_SECRET ?? '',
  CONTENT_KEY: keep('CONTENT_KEY', key),
  SCHEDULER_BEARER_SHA256: sha(shared.SCHEDULER_BEARER),
  WORKER_DEV_SECRET: shared.WORKER_DEV_SECRET,
  RECOVER_DEV_AUTH: '1',
  VISION_MODE: prev.VISION_MODE || 'mock',
  WEB_URL: 'http://localhost:3000',
  REVALIDATE_SECRET: shared.REVALIDATE_SECRET,
};

const rootEnv = {
  DB_URL: dbUrl,
  WORKER_URL: 'http://localhost:3001',
  WEB_URL: 'http://localhost:3000',
  SCHEDULER_BEARER: shared.SCHEDULER_BEARER,
  READY_SECRET: shared.READY_SECRET,
  STAFF_ASSERTION_KEY_CURRENT: shared.STAFF_ASSERTION_KEY_CURRENT,
  STAFF_ASSERTION_KEY_VERSION: shared.STAFF_ASSERTION_KEY_VERSION,
  WORKER_DEV_SECRET: shared.WORKER_DEV_SECRET,
  REVALIDATE_SECRET: shared.REVALIDATE_SECRET,
};

writeEnv(files.web, web, 'recover-web local environment');
writeEnv(files.worker, worker, 'recover-worker local environment');
writeEnv(files.root, rootEnv, 'dev scheduler and test harness secrets');

// Vault: staff assertion key v<N> plus current/previous pointers (G-17).
const version = shared.STAFF_ASSERTION_KEY_VERSION;
const upsert = (name, value) => `
  do $$ begin
    if exists (select 1 from vault.secrets where name = '${name}') then
      perform vault.update_secret((select id from vault.secrets where name = '${name}'), '${value}');
    else
      perform vault.create_secret('${value}', '${name}');
    end if;
  end $$;`;
for (const v of [shared.STAFF_ASSERTION_KEY_CURRENT, version]) {
  if (!/^[A-Za-z0-9_-]+$/.test(v)) throw new Error('dev-env: unexpected characters in a generated secret');
}
const sql = [
  upsert(`staff_assertion_key_v${version}`, shared.STAFF_ASSERTION_KEY_CURRENT),
  upsert('staff_assertion_key_current', version),
  upsert('staff_assertion_key_previous', ''),
].join('\n');
execFileSync('psql', [dbUrl, '-v', 'ON_ERROR_STOP=1', '-q', '-c', sql], { stdio: ['ignore', 'ignore', 'inherit'] });

const names = (o) => Object.keys(o).join(', ');
console.log(`dev-env: wrote apps/web/.env.local (${names(web)})`);
console.log(`dev-env: wrote apps/worker/.env.local (${names(worker)})`);
console.log(`dev-env: wrote .env.local (${names(rootEnv)})`);
console.log(`dev-env: Vault staff_assertion_key_v${version} + current/previous pointers upserted`);
